name: mpt-30b-chat_composer_chatv2

compute:
  gpus: 8  # Number of GPUs to use

  ## These configurations are optional
  # cluster: r0z0 # Name of the cluster to use for this run
  # gpu_type: h100_80gb # Type of GPU to use.

integrations:
# Clone and install the llm-foundry repo so we can run scripts from it
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  pip_install: -e .[gpu]
  ssh_clone: false # Should be true if using a private repo
  git_commit: 496b50bd588b1a7231fe54b05d70babb3620fc72
- git_repo: mosaicml/composer
  integration_type: git_repo
  path: /workspace/composer
  ssh_clone: false # Should be true if using a private repo
  pip_install: -e .[all]
# Uncomment and fill in to log to WandB. Also uncomment the loggers section near the bottom of the yaml
# - integration_type: wandb
#   entity: mosaic-ml
#   project: support-bot-demo-composer-chatv2

# cd into the llm-foundry/scripts directory and run the train.py script
command: |
  cd llm-foundry/scripts
  composer train/train.py /mnt/config/parameters.yaml || (echo "Command failed - killing python" && pkill python && exit 1)

image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04 # Use the Docker image provided by MosaicML

# The parameters section is mounted to /mnt/config/parameters.yaml in the container
# The mounted file is then passed directly to the train.py script
# See LLM-foundry llmfoundry/scripts/train.py to see how the parameters are used in code
parameters:
  # Path to load the weights from the previous step
  load_path: CLOUD://BUCKET_NAME/support-bot-demo/checkpoints/mpt-30b-chat_composer-codebase/latest-rank0.pt.symlink
  load_weights_only: true # Only load the weights for finetuning, discarding any other state from previous training

  # Checkpoint to local filesystem or remote object store
  save_interval: 1ep # How frequently to save checkpoints
  save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
  save_folder: CLOUD://BUCKET_NAME/support-bot-demo/checkpoints/mpt-30b-chat_composer_chatv2/
  save_weights_only: true # Since we only need the weights for the next step, we can reduce the size of the checkpoint

  # Maximum sequence length of the model
  # For MPT, you can change this to a different number if you would like to train on longer sequences
  # Note that you would also need to reprocess your data to contain longer sequences
  max_seq_len: 8192

  # Random seed to ensure reproducibility
  global_seed: 17

  # Run Name
  run_name: # If left blank, will be read from env var $RUN_NAME

  # Model
  # This section is used by LLM-foundry to construct the model
  model:
    name: hf_causal_lm
    pretrained: false
    pretrained_model_name_or_path: mosaicml/mpt-30b
    init_device: mixed
    config_overrides:
      max_seq_len: ${max_seq_len}
      attn_config:
        attn_impl: triton
        attn_uses_sequence_id: false

  train_loader:
    name: finetuning
    dataset:
      hf_name: sam-mosaic/chat-v2
      split: train
      max_seq_len: ${max_seq_len}
      allow_pad_trimming: false
      decoder_only_format: true
      # Use `python llmfoundry/data/packing.py --yaml-path /path/to/this/yaml/ ...`
      # to profile this run's optimal packing_ratio as it depends on GPU count,
      # batch size, sequence length. Turning on packing by setting packing_ratio
      # here will pack multiple examples into one sequence for increased efficiency.
      # For the mosaicml/dolly_hhrlhf and max sequence length 2048,
      # 3 is a good packing_ratio that will not cause any examples to be trimmed.
      # As an approximate rule of thumb, if you, for example, double max_seq_len you can double packing_ratio.
      # packing_ratio:
      shuffle: true
    drop_last: true
    num_workers: 8

  eval_loader:
    name: finetuning
    dataset:
      hf_name: sam-mosaic/chat-v2
      split: test
      max_seq_len: ${max_seq_len}
      allow_pad_trimming: false
      decoder_only_format: true
      # packing_ratio:
      shuffle: true
    drop_last: false
    num_workers: 8

  # Learning rate scheduler
  # see LLM-foundry llmfoundry/utils/builders.py::build_scheduler for other built-in options
  scheduler:
    name: linear_decay_with_warmup
    t_warmup: 50ba
    alpha_f: 0

  # Optimizer
  # see LLM-foundry llmfoundry/utils/builders.py::build_optimizer for other built-in options
  optimizer:
    name: decoupled_lionw
    lr: 0.0000005
    betas:
    - 0.9
    - 0.99
    weight_decay: 0


  # Algorithms to apply
  # see LLM-foundry llmfoundry/utils/builders.py::build_algorithm for other built-in options
  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  # Run configuration
  max_duration: 1ep # Maximum duration of the run. Change to something shorter (e.g. 10ba) for a quick test run
  eval_interval: 2000ba # How frequently to evaluate the model
  eval_first: true # Whether to evaluate the model before training
  eval_subset_num_batches: -1 # How many batches to evaluate on. -1 means evaluate on the entire dataset
  global_train_batch_size: 64  # Global batch size. This is the batch size across all GPUs and should be 8*num_gpus
  seed: ${global_seed}
  device_eval_batch_size: 2 # Evaluation batch size per GPU
  device_train_microbatch_size: 1 
  precision: amp_bf16

  # Configuration settings for FSDP
  # https://docs.mosaicml.com/projects/composer/en/latest/notes/distributed_training.html#fullyshardeddataparallel-fsdp
  # for more information about FSDP in Composer
  fsdp_config:
    sharding_strategy: FULL_SHARD
    mixed_precision: PURE
    activation_checkpointing: true
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    verbose: false

  # Logging configuration
  progress_bar: false
  log_to_console: true
  console_log_interval: 1ba
  python_log_level: debug

  # Uncomment to log to WandB
  # see LLM-foundry llmfoundry/utils/builders.py::build_logger for other built-in options
  # loggers:
  #   wandb: {}

  # Callbacks
  # see LLM-foundry llmfoundry/utils/builders.py::build_callback for other built-in options
  callbacks:
    # Periodically generate text from the model, uncomment only if you are logging to WandB
    # generate_callback:
    #   batch_log_interval: 500
    #   do_sample: true
    #   max_new_tokens: 100
    #   prompts:
    #   - The quick brown fox jumps over
    #   - |-
    #     Vegan Banana Bread
    #     Instructions:
    #     1.
    #   - The other day I was explaining what generative AI is to my five year old.
    #   - We are a global semiconductor company primarily offering
    #   - Our company had revenue of
    #   - Our business operations are subject to numerous risks, including
    #   - What was AMD's revenue in 2019?
    #   - What is net operating income?
    #   temperature: 1
    #   top_k: 50
    #   top_p: 0.95
    #   use_cache: true
    # Log information about the processing speed of the model
    speed_monitor:
      window_size: 10
    # Log the learning rate over the course of training
    lr_monitor: {}
    # Log information about the memory usage of the model
    memory_monitor: {}
    # Log an estimate of how long the training run has left to complete
    runtime_estimator: {}

  icl_max_seq_len: 2048
  icl_tasks:
  -
    label: arc_easy
    dataset_uri: eval/local_data/world_knowledge/arc_easy.jsonl
    num_fewshot: [0]
    icl_task_type: multiple_choice
    continuation_delimiter: 'Answer: '