integrations:
  - integration_type: git_repo
    git_repo: evanfabry/benchmarks-adafactor
    git_branch: resume
    pip_install: -r llm/requirements.txt
    ssh_clone: False
  - integration_type: git_repo
    git_repo: flanlabs/lm-evaluation-harness
    git_branch: master
    pip_install: .
    ssh_clone: False
  - integration_type: git_repo
    git_repo: Lightning-AI/metrics
    pip_install: .
    ssh_clone: False
  # - integration_type: git_repo
  #   git_repo: EleutherAI/lm-evaluation-harness
  #   git_branch: master
  #   pip_install: .
  #   ssh_clone: False

command: |
  cd benchmarks-adafactor/llm
  cat /mnt/config/parameters.yaml
  pip list
  WANDB_API_KEY=011ca75d0cb58d449a9957690456b143d909f532 GCS_KEY=GOOG1EYYKKHYUK574G4HKFTRYKLQ22KM33FIW4QRQZ5QUYSLV7UO34U7H6GXA GCS_SECRET=8WmsrawOqngGi0zJPcPm2ckUX5XY/2UIx7Z5vzsA TOKENIZERS_PARALLELISM=true composer main.py /mnt/config/parameters.yaml

image: mosaicml/pytorch:1.12.1_cu116-python3.9-ubuntu20.04
optimization_level: 0

gpu_num: 16
# run_name: &run_name mgpt-760m-${gpu_num}-gpus-${resume_batch}-step-${project}
# run_name: &run_name mosaic-gpt-760m-16-gpus-12800-13824-step
run_name: &run_name mosaic-gpt-760m-16-gpus-0

gpu_type: a100_40gb
cluster: r7z7

# The below is injected as a YAML file:
parameters:
  data_remote: &data_remote gs://llm_data_public/c4/my-copy-c4
  data_local: &data_local ./my-copy-c4
  max_seq_len: &max_seq_len 2048
  tokenizer_name: &tokenizer_name gpt2

  # Run Name
  run_name: *run_name

  # # 1B model
  # model:
  #   name: mosaic_gpt
  #   device: meta
  #   tokenizer_name: *tokenizer_name
  #   d_model: 2048
  #   n_heads: 16 # Modified 24->16 so that d_head == 128 to statisfy FlashAttention
  #   n_layers: 24
  #   mlp_ratio: 4
  #   max_seq_len: *max_seq_len
  #   vocab_size: 50257
  #   init_std: 0.02
  #   attn_pdrop: 0.0
  #   resid_pdrop: 0.0
  #   emb_pdrop: 0.0
  #   attn_impl: flash

  # 760M model
  model:
    name: mosaic_gpt
    device: meta
    tokenizer_name: *tokenizer_name
    d_model: 1536
    n_heads: 12 # Modified 16->12 so that d_head == 128 to statisfy FlashAttention
    n_layers: 24
    mlp_ratio: 4
    max_seq_len: *max_seq_len
    vocab_size: 50257
    init_std: 0.02
    attn_pdrop: 0.0
    resid_pdrop: 0.0
    emb_pdrop: 0.0
    attn_impl: flash

  # # 30B model
  # model:
  #   name: mosaic_gpt
  #   device: meta
  #   tokenizer_name: *tokenizer_name
  #   d_model: 7168
  #   n_heads: 56
  #   n_layers: 48
  #   mlp_ratio: 4
  #   max_seq_len: *max_seq_len
  #   vocab_size: 50257
  #   init_std: 0.02
  #   attn_pdrop: 0.0
  #   resid_pdrop: 0.0
  #   emb_pdrop: 0.0
  #   attn_impl: flash

  # Dataloaders
  train_loader:
    name: c4
    dataset:
      remote: *data_remote
      local: *data_local
      split: train
      shuffle: true
      prefetch: 1_000_000
      tokenizer_name: *tokenizer_name
      max_seq_len: *max_seq_len
      group_method: concat
    drop_last: true
    num_workers: 8
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  eval_loader:
    name: c4
    dataset:
      remote: *data_remote
      local: *data_local
      split: val
      shuffle: false
      prefetch: 1000
      tokenizer_name: *tokenizer_name
      max_seq_len: *max_seq_len
      group_method: truncate
    drop_last: false
    num_workers: 8
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  # Optimization
  scheduler:
    name: cosine_with_warmup
    t_warmup: 100ba
    alpha_f: 0.1

  optimizer:
    name: decoupled_adamw
    # lr: 0.001
    lr: 1.0e-4
    betas:
      - 0.9
      - 0.95
    eps: 1.0e-08
    weight_decay: 0.0

  max_duration: 24800ba # ~ 26B tokens
  # max_duration: 49600ba # ~ 26B tokens
  eval_interval: 2000ba
  global_train_batch_size: 512
  # max_duration: 143100ba # ~ 600B tokens
  # eval_interval: 10000ba
  # global_train_batch_size: 2048
  grad_clip_norm: 1.0

  # System
  seed: 18
  # device_train_microbatch_size: 16
  device_train_microbatch_size: 8
  # device_train_microbatch_size: auto
  grad_accum: 2
  precision: bf16

  # FSDP
  fsdp_config:
    sharding_strategy: FULL_SHARD
    min_params: 2e8
    mixed_precision: DEFAULT
    activation_checkpointing: true
    activation_cpu_offload: false
    verbose: true

  # Logging
  progress_bar: false
  log_to_console: true

  callbacks:
    speed_monitor:
      window_size: 10
    lr_monitor: {}
    memory_monitor: {}
    # lm_eval_harness:
    #   every_n_batches: 128

  loggers:
    wandb:
      project: resume_debugging
      entity: llm
    remote_uploader_downloader:
      bucket: llm_models

  # Checkpoint to local filesystem or remote object store
  save_interval: 128ba
  save_num_checkpoints_to_keep: 1 # Important, this cleans up checkpoints saved to DISK
  save_folder: ./{run_name}/checkpoints
  save_overwrite: true
  # load_object_store:
  #   bucket: llm_models
  # load_path: mosaic-gpt-760m-16-gpus-divergent/checkpoints/ep0-ba12800-rank0.pt
  # resume_batch: 13824
