# Whether to run the various GLUE jobs serially or in parallel
parallel: true

# Basic run configuration, additionall details will be added to this name for each GLUE task, and each random seed
base_run_name: glue-finetuning-benchmark-test
default_seed: 1111
precision: bf16

# Saving and loading
pretrained_model_name: 'bert-base-uncased'
starting_checkpoint_load_paths: 
    - https://storage.googleapis.com/alex_bert_checkpoints/bert/dc-2022-07-v2/bert-dc-2022-07-baseline--seed9407/checkpoints/ep0-ba68796-rank0-36826.074846wct
local_pretrain_checkpoint_folder: ./local-bert-checkpoints/
save_finetune_checkpoint_prefix: ./local-finetune-checkpoints/
save_finetune_checkpoint_folder: ${save_finetune_checkpoint_prefix}/${base_run_name}

# Loggers
logger:
  wandb:
    project: daniel-debug
    entity: mosaic-ml

# Callbacks
callbacks:
  lr_monitor: {}
  speed_monitor: {}

# Task configuration
# Any arguments specified under a task will get passed along as trainer kwargs for that task
tasks:
  mnli:
    _target_: src.tasks.glue_jobs.MNLIJob
    # We keep one MNLI checkpoint locally so that we can start finetuning of 
    # RTE, MRPC and STS-B from the MNLI checkpoint
    save_num_checkpoints_to_keep: 1
  rte:
    _target_: src.tasks.glue_jobs.RTEJob
    save_num_checkpoints_to_keep: 0
  qqp:
    _target_: src.tasks.glue_jobs.QQPJob
    save_num_checkpoints_to_keep: 0
  qnli:
    _target_: src.tasks.glue_jobs.QNLIJob
    save_num_checkpoints_to_keep: 0
  sst2:
    _target_: src.tasks.glue_jobs.SST2Job
    save_num_checkpoints_to_keep: 0
  stsb:
    _target_: src.tasks.glue_jobs.STSBJob
    save_num_checkpoints_to_keep: 0
  mrpc:
    _target_: src.tasks.glue_jobs.MRPCJob
    save_num_checkpoints_to_keep: 0
  cola:
    _target_: src.tasks.glue_jobs.COLAJob
    save_num_checkpoints_to_keep: 0

# Seeds to run for each task
task_seeds:
  mnli_seeds: [1]
  qqp_seeds: [3]