# Whether to run the various GLUE jobs serially or in parallel
parallel: true

# Basic run configuration, additionall details will be added to this name for each GLUE task, and each random seed
base_run_name: glue-finetuning-benchmark-test
default_seed: 1111
precision: bf16

# Saving and loading
pretrained_model_name: 'bert-base-uncased'
starting_checkpoint_load_path: https://storage.googleapis.com/alex_bert_checkpoints/bert/dc-2022-07-v2/bert-dc-2022-07-baseline--seed9407/checkpoints/ep0-ba68796-rank0-36826.074846wct
local_pretrain_checkpoint_folder: ./local-bert-checkpoints/
save_finetune_checkpoint_prefix: ./local-finetune-checkpoints/
save_finetune_checkpoint_folder: ${save_finetune_checkpoint_prefix}/${base_run_name}

# Loggers
logger:
  wandb:
    project: daniel-debug
    entity: mosaic-ml

# Callbacks
callbacks:
  lr_monitor: {}
  speed_monitor: {}

# Scheduler
scheduler:
  name: linear_with_warmup
  t_warmup: 0.06dur

# Task configuration
tasks:
  mnli:
    seeds: [1]
    # Specify any extra task-specific arguments for the trainer here
    trainer_kwargs:
      # We keep one MNLI checkpoint locally so that we can start finetuning of 
      # RTE, MRPC and STS-B from the MNLI checkpoint
      save_num_checkpoints_to_keep: 1
  rte:
    trainer_kwargs:
      save_num_checkpoints_to_keep: 0
  qqp:
    seeds: [3]
    trainer_kwargs:
      save_num_checkpoints_to_keep: 0
  qnli:
    trainer_kwargs:
      save_num_checkpoints_to_keep: 0
  sst2:
    trainer_kwargs:
      save_num_checkpoints_to_keep: 0
  stsb:
    trainer_kwargs:
      save_num_checkpoints_to_keep: 0
  mrpc:
    trainer_kwargs:
      save_num_checkpoints_to_keep: 0
  cola:
    trainer_kwargs:
      save_num_checkpoints_to_keep: 0