name: Lint

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
  workflow_dispatch: {}
defaults:
  run:
    working-directory: .
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        include:
        - name: bert-pytest
          container: mosaicml/pytorch:1.13.1_cpu-python3.10-ubuntu20.04
        - name: cifar-pytest
          container: mosaicml/pytorch_vision:1.13.1_cpu-python3.10-ubuntu20.04
        - name: deeplab-pytest
          container: mosaicml/pytorch_vision:1.13.1_cpu-python3.10-ubuntu20.04
        - name: llm-pytest
          container: mosaicml/pytorch:1.13.1_cpu-python3.10-ubuntu20.04
        - name: resnet-pytest
          container: mosaicml/pytorch_vision:1.13.1_cpu-python3.10-ubuntu20.04
    name: ${{ matrix.name }}
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Setup
      run: |
        set -ex
        export PATH=/composer-python:$PATH
        python -m pip install --upgrade pip wheel
    - name: Lint
      run: |
        export PATH=/composer-python:$PATH
        bash scripts/lint_subdirectory.sh ${{ matrix.subdir }}
