name: Test

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*
  workflow_dispatch: {}
defaults:
  run:
    working-directory: .
jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python_version:
        - '3.9'
        subdir:
        - bert
        - cifar
        - deeplab
        - llm
        - resnet
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Setup
      run: |
        set -ex
        python -m pip install --upgrade pip wheel
    - name: Test
      run: |
        bash scripts/test_subdirectory.sh ${{ matrix.subdir }}
